### ISSUE TITLE
Paniced trying to unwrap Err(NoSuchGlyph)

### ISSUE THREAD

**Issue by gustafla** [l4l/yofi#30]
Hi and sorry for not investigating this further. When I set my font as 'monospace' or 'Terminus' (should be the same thing as I created an alias in fonts.conf), I get the following panic when I try to launch. Running Arch Linux and the font in question is `terminus-font` from `community` (https://archlinux.org/packages/community/any/terminus-font/). Thanks for the awesome work so far!

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoSuchGlyph', /home/gustafla/.cargo/git/checkouts/raqote-e2149927d9facb18/27cfc13/src/draw_target.rs:784:39
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.49.0-src/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.49.0-src/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /build/rust/src/rustc-1.49.0-src/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /build/rust/src/rustc-1.49.0-src/library/core/src/result.rs:973:23
   4: raqote::draw_target::DrawTarget::draw_text
             at /home/gustafla/.cargo/git/checkouts/raqote-e2149927d9facb18/27cfc13/src/draw_target.rs:784:22
   5: <yofi::draw::list_view::ListView<It> as yofi::draw::Drawable>::draw
             at ./src/draw/list_view.rs:198:17
   6: <yofi::draw::Widget<It> as yofi::draw::Drawable>::draw
             at ./src/draw.rs:63:34
   7: yofi::surface::Surface::redraw
             at ./src/surface.rs:161:32
   8: yofi::draw
             at ./src/main.rs:180:5
   9: yofi::main
             at ./src/main.rs:155:13
  10: core::ops::function::FnOnce::call_once
             at /build/rust/src/rustc-1.49.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by l4l** [comment]
I guess some of the unicode glyphs are missing in the font. There's a related issue in third party library: https://github.com/jrmuizel/raqote/issues/150. Unfortunately, I am not sure there's a workaround except choosing a different font. Nevertheless I think the issue still make sense.
