### ISSUE TITLE
Initial roundtrip failed!: NoCompositerListening

### ISSUE THREAD

**Issue by jirislav** [l4l/yofi#54]
Hi,

I've successfully installed (and tried out) `yofi` from sources, but after some additional packages installation (on Ubuntu 21.04) and reboot I get this error, being unable to run `yofi` at all :/

```sh
RUST_BACKTRACE=full yofi --verbose
# note that the /tmp/yofi.log exists, but is empty
```

Resulting output of the command above is:

```
thread 'main' panicked at 'Initial roundtrip failed!: NoCompositorListening', src/main.rs:111:14
stack backtrace:
   0:     0x563bb5e1088a - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x563bb5e1088a - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x563bb5e1088a - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x563bb5e1088a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x563bb5cbd3ec - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x563bb5e0fff1 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x563bb5e0f8fb - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x563bb5e0f8fb - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x563bb5e0f8fb - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x563bb5e0f8fb - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x563bb5e0f8fb - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x563bb5e2bc68 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x563bb5e2bc34 - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x563bb5e2bbed - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x563bb5cbab20 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x563bb5cc19b2 - core::option::expect_none_failed::h6154dc750ae47ade
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
  16:     0x563bb5c2ee15 - yofi::main::hca3ac633ec3ea871
  17:     0x563bb5c249b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h61ff76ebcd542a68
  18:     0x563bb5c50e35 - main
  19:     0x7f89e89a0565 - __libc_start_main
  20:     0x563bb5c2007e - _start
  21:                0x0 - <unknown>
```

---

It might be related, but I've installed `tlp` for power management and `acpi-call-dkms`.

**Comment by jirislav** [comment]
Hmm, after some investigation, it looks like I'm unable to run Wayland session anymore. For some reason, I cannot see the option of `Ubuntu (wayland)` at the login screen.

Also, when inspecting running processes, there is no `XWayland` as usual. so that might be that cause.

I think the above error message is the result of running inside a X11, so #23 is probably related to this issue.
