### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by CozzyBro2** [l4l/yofi#71]
Installed by cloning the repository and building with `cargo build --release`, and then ran using the command listed in the log below, this run-time error is emitted: 

```rust
gavin@arch ~/yofi (master)> RUST_BACKTRACE=full cargo run --release
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/yofi`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/font/fdue.rs:65:14
stack backtrace:
   0:     0x563b53f96a65 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563b53f96a65 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b53f96a65 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563b53f96a65 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563b53e5154c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x563b53f95184 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x563b53f95c5b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563b53f95c5b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563b53f95c5b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x563b53f94d89 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x563b53f94d89 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x563b53faeeee - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:517:13
  12:     0x563b53faee8c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563b53faee3d - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x563b53dc9970 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x563b53dc98bc - core::panicking::panic::h1a48d878ff3dcd40
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:50:5
  16:     0x563b540e0cd5 - <yofi::font::fdue::Font as yofi::font::FontBackend>::default::he4a2f9f4d1a13b7f
  17:     0x563b5409b3b4 - yofi::config::params::<impl core::convert::From<&yofi::config::Config> for yofi::draw::input_text::Params>::from::h5706ebf288026551
  18:     0x563b540c2f62 - yofi::draw::h39c75ad96fc7866d
  19:     0x563b540bf6b7 - yofi::main::h60d167a6e57d3f47
  20:     0x563b540dd363 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfdec4b4d300533eb
  21:     0x563b540abb21 - main
  22:     0x7f5536bb7b25 - __libc_start_main
  23:     0x563b53ddbd4e - _start
  24:                0x0 - <unknown>
gavin@arch ~/yofi (master) [101]>
```

**Comment by l4l** [comment]
That one looks strange, linked PR is a workaround for the issue by removing a monospace constraint (which for some reason doesn't work: https://github.com/fschutt/rust-fontconfig/issues/6).

Also, keep in mind that you could manually specify the font in [the config](https://github.com/l4l/yofi/blob/master/README.md#configuring) with `font` parameter.
